first-task
ok-technopolis-autumn-2022/Andrey_Cheshev pull request #1
Opened 2022-10-02 23:38 UTC by Queenore

2022-10-03 09:12 UTC, fromanywhere requested changes
В целом неплохо. Нужно больше внимания уделить футеру. Дорабатываем после сегодняшней лекции тут же

2022-10-03 09:12 UTC, fromanywhere commented on index.html
> +<footer>
Странно — зачем же Вам пустой футер?

2022-10-03 09:12 UTC, fromanywhere commented on index.html
> +            <input value="HTML">
Какого типа этот input? Как он работает?

2022-10-03 11:38 UTC, Queenore commented
Не подскажете, что значит доработать футер (без стилей не получится сделать все в одну строку, разделив на логические группы)?  Возможно заменить первый div на span в футере....

2022-10-03 12:32 UTC, fromanywhere commented
Пусть будет в несколько строк, это сейчас непринципиально

2022-10-05 10:27 UTC, fromanywhere requested changes

2022-10-05 10:27 UTC, fromanywhere commented on index.html
> +    <span role="radio">
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radio_role radiogroup, aria-label

2022-10-07 12:22 UTC, fromanywhere approved these changes

2022-10-07 12:24 UTC, merged