part2-css
ok-technopolis-autumn-2022/Andrey_Cheshev pull request #2
Opened 2022-10-31 23:26 UTC by Queenore

2022-11-01 08:56 UTC, fromanywhere requested changes

2022-11-01 08:56 UTC, fromanywhere commented on style.css
> +    height: 402px;
<img width="663" alt="image" src="https://user-images.githubusercontent.com/1042969/199194858-1700f4d8-ba04-486c-9a34-918393d8d86a.png">

2022-11-01 08:56 UTC, fromanywhere commented on style.css
> +    align-items: center;
На узком экране недоступна не только левая, но и правая части приложения (нет скролла) 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/1042969/199194983-82e6862f-4638-4cdf-9427-5bf10c692bef.png">

2022-11-01 08:56 UTC, fromanywhere commented on style.css
> +    display: none;
Кнопка не появляется при клавиатурной навигации

2022-11-01 08:56 UTC, fromanywhere commented on style.css
> +    font-style: italic;
Правая часть поля ввода некликабельна 
<img width="595" alt="image" src="https://user-images.githubusercontent.com/1042969/199195255-88e70352-894c-44ec-b390-3abd077d9d71.png">

2022-11-01 08:56 UTC, fromanywhere commented on style.css
> +    font-style: normal;
Аналогично, здесь правая часть элемента не ловит клик — неясно, куда нажать, чтобы печатать (раз уже у Вас там поле ввода) 
<img width="602" alt="image" src="https://user-images.githubusercontent.com/1042969/199195467-edd43308-5093-4726-aa67-65dcbc62840c.png">

2022-11-01 08:56 UTC, fromanywhere commented on style.css
> +    width: 562px;
по идее эта ширина не нужна — она должна браться от родителя

2022-11-01 08:56 UTC, fromanywhere commented on style.css
> +    display: none;
Здесь умерла клавиатурная навигация

2022-11-01 08:56 UTC, fromanywhere commented on style.css
> +    top: 25%;
На чем основана цифра в 25%? Почему %?

2022-11-01 08:56 UTC, fromanywhere commented on style.css
> +    position: absolute;
Было бы правильнее выравнивать не руками. Например, флексом

2022-11-01 08:56 UTC, fromanywhere commented on style.css
> +    border: 1px solid #EBDFDF;
Тут фильтры прыгают по горизонтали при переключении

2022-11-01 08:56 UTC, fromanywhere commented on style.css
> +    content: url("completed.png");
графика неретиновая

2022-11-08 08:03 UTC, fromanywhere requested changes

2022-11-08 08:03 UTC, fromanywhere commented on index.html
> +                        <label class="new-checkbox" for="check1" tabindex="0"> </label>
убираем все табиндексы, они здесь не нужны

2022-11-08 08:03 UTC, fromanywhere commented on index.html
> +                <input id="new-todo-id" class="new-todo-text" type="text" placeholder="What needs to be done?" aria-label="add todo">
и id не нужен

2022-11-08 08:03 UTC, fromanywhere commented on index.html
> +                            <img src="close.svg" alt="close button">
картинки кладем фоновыми изображениями

2022-11-08 08:03 UTC, fromanywhere commented on index.html
> +                            <img src="close.svg" alt="close button">
тексты нужно как-то сохранить при этом для читалок

2022-11-08 08:03 UTC, fromanywhere commented on style.css
> +    display: none;
Всё еще умерла

2022-11-08 08:03 UTC, fromanywhere commented on style.css
> +    display: none;
здесь тоже клавиатурная навигация не работает (не могу поставить галку пробелом)

2022-11-14 02:36 UTC, Queenore commented on style.css
> +    display: none;
Сделал навигацию с помощью стрелок внутри radiogroup (Алина в лекции сказала , что такой вариант приемлем).

2022-11-14 09:26 UTC, fromanywhere approved these changes

2022-11-14 09:47 UTC, merged